### PR TITLE
Use convex hull to simplify MultiPolygon authority boundaries. #4

### PR DESCRIPTION
**Pull request by dabreegster**
As a side effect, reduce file size from 2MB to 700KB.

See issue for the rationale. Having a single `Polygon` for boundaries means things like the route snapper will work as intended in areas split into mainland and islands. As a downside, the boundaries shown on the ATIP homepage will overlap each other. The highlighted boundaries will also look a bit odd sometimes, but the previous thing also looked choppy and odd.

Ideally we would solve this "upstream" in https://github.com/acteng/boundaries or wherever is producing the raw input.

I've chosen to use Node because it's quick and easy, [Turf](https://turfjs.org/docs/#convex) is great, and it has reproducible builds (with `package-lock.json`). We can consolidate data pipelines somehow later.

TODO for me: regenerate all route snapping files, copy the fixed authority file to ATIP, and re-deploy prod. (I'll do this tonight when I'm home with a faster machine)

### CODE REVIEW

**Comment by dabreegster** [comment]
CC @Sparrow0hawk. (I'll add you in the Github teams so I can tag you as a reviewer properly)

**Comment by dabreegster** [comment]
Before:
Screenshot from 2023-02-06 15-16-48
After:
Screenshot from 2023-02-06 15-16-18

**Comment by dabreegster** [comment]
For Portsmouth, I still think the output in this PR is more usable than an earlier fix, https://github.com/acteng/schema/blob/main/boundaries/lads_tas_combined.geojson:


Logic for that is https://github.com/acteng/schema/blob/d22870e794da9a1cda14a537e171729603d8708b/code/boundaries.R#L64

**Comment by Sparrow0hawk** [comment]
This looks good to me. 

I agree we probably want to look at fixing this at source.

Can we deploy this to https://github.com/acteng/atip as a quick test before pushing to prod? (Don't think it's essential)

**Comment by dabreegster** [comment]
> Can we deploy this to https://github.com/acteng/atip as a quick test before pushing to prod? (Don't think it's essential)

Yes, that'll happen. I'll ping on Slack before pushing to prod.

... but now I'm realizing all copies of ATIP grab the route file from prod. Going to add in something there to toggle this around, so we can test this change.

**Comment by dabreegster** [comment]
Boundary overlapping on main screen:
Screenshot from 2023-02-06 21-28-23
Portsmouth working as intended:

https://user-images.githubusercontent.com/1664407/217092180-2f7d68bf-ced3-44e2-b8fc-eaff5d85d307.mp4

**Comment by dabreegster** [comment]
Try out at https://acteng.github.io/atip/scheme.html?authority=Portsmouth#12.23/50.82835/-1.09318.

I'll merge this now, ready to deploy to prod whenever. I'll confirm with y'all on slack first.

**Comment by Robinlovelace** [comment]
Looking great. Sorry for being slow on the case and many thanks for quick work on this :fire:

**Pull request merged**
